using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Product.DataAccess.Models
{
    public class SlaesOrderHeaderAndLines
    {
        public class Rootobject
        {
            public string odatacontext { get; set; }
            public Value[] value { get; set; }
        }
        public class Value
        {
            public string odataetag { get; set; }
            public string Document_Type { get; set; }
            public string No { get; set; }
            public string Sell_to_Customer_No { get; set; }
            public string Sell_to_Customer_Name { get; set; }
            public string Quote_No { get; set; }
            public string Sell_to_Address { get; set; }
            public string Sell_to_Address_2 { get; set; }
            public string Sell_to_City { get; set; }
            public string Sell_to_County { get; set; }
            public string Sell_to_Post_Code { get; set; }
            public string Sell_to_Contact_No { get; set; }
            public string Sell_to_Contact { get; set; }
            public int No_of_Archived_Versions { get; set; }
            public string Posting_Description { get; set; }
            public string Master_Job_No { get; set; }
            public int RetainagePercent { get; set; }
            public string Posting_Date { get; set; }
            public string Order_Date { get; set; }
            public string Document_Date { get; set; }
            public string Due_Date { get; set; }
            public string Requested_Delivery_Date { get; set; }
            public string Promised_Delivery_Date { get; set; }
            public string Your_Reference { get; set; }
            public string External_Document_No { get; set; }
            public string Salesperson_Code { get; set; }
            public string Campaign_No { get; set; }
            public string Opportunity_No { get; set; }
            public string Responsibility_Center { get; set; }
            public string Assigned_User_ID { get; set; }
            public string Job_Queue_Status { get; set; }
            public string Status { get; set; }
            public string ValidateAddress { get; set; }
            public string Blind_Shipment_Customer_No { get; set; }
            public string Opportunity_ID { get; set; }
            public int CRM_Sales_Amount { get; set; }
            public int CRM_Cost_Amount { get; set; }
            public int CRM_Margin_Amount { get; set; }
            public bool Closed { get; set; }
            public string SO_Status { get; set; }
            public string CFDI_Purpose { get; set; }
            public string CFDI_Relation { get; set; }
            public string WorkDescription { get; set; }
            public string Currency_Code { get; set; }
            public string Payment_Terms_Code { get; set; }
            public string Payment_Method_Code { get; set; }
            public bool Tax_Liable { get; set; }
            public string Tax_Area_Code { get; set; }
            public string SelectedPayments { get; set; }
            public string Shortcut_Dimension_1_Code { get; set; }
            public string Shortcut_Dimension_2_Code { get; set; }
            public int Payment_Discount_Percent { get; set; }
            public string Pmt_Discount_Date { get; set; }
            public int CRM_Cost_Amount_Copy { get; set; }
            public int CRM_Sales_Amount_Copy { get; set; }
            public int CRM_Margin_Amount_Copy { get; set; }
            public string Opportunity_ID_Copy { get; set; }
            public string Direct_Debit_Mandate_ID { get; set; }
            public string ShippingOptions { get; set; }
            public string Ship_to_Code { get; set; }
            public string Ship_to_Name { get; set; }
            public string Ship_to_Address { get; set; }
            public string Ship_to_Address_2 { get; set; }
            public string Ship_to_City { get; set; }
            public string Ship_to_County { get; set; }
            public string Ship_to_Post_Code { get; set; }
            public string Ship_to_Country_Region_Code { get; set; }
            public string Ship_to_UPS_Zone { get; set; }
            public bool Ready_for_Shipping { get; set; }
            public string Ship_to_Contact { get; set; }
            public string Shipment_Method_Code { get; set; }
            public string Shipping_Agent_Code { get; set; }
            public string Shipping_Agent_Service_Code { get; set; }
            public string Package_Tracking_No { get; set; }
            public string BillToOptions { get; set; }
            public string Bill_to_Name { get; set; }
            public string Bill_to_Address { get; set; }
            public string Bill_to_Address_2 { get; set; }
            public string Bill_to_City { get; set; }
            public string Bill_to_County { get; set; }
            public string Bill_to_Post_Code { get; set; }
            public string Bill_to_Contact_No { get; set; }
            public string Bill_to_Contact { get; set; }
            public string Location_Code { get; set; }
            public string Shipment_Date { get; set; }
            public string Shipping_Advice { get; set; }
            public string Outbound_Whse_Handling_Time { get; set; }
            public string Shipping_Time { get; set; }
            public bool Late_Order_Shipping { get; set; }
            public string Transaction_Specification { get; set; }
            public string Transaction_Type { get; set; }
            public string Transport_Method { get; set; }
            public string Exit_Point { get; set; }
            public string Area { get; set; }
            public int Prepayment_Percent { get; set; }
            public bool Compress_Prepayment { get; set; }
            public string Prepmt_Payment_Terms_Code { get; set; }
            public string Prepayment_Due_Date { get; set; }
            public int Prepmt_Payment_Discount_Percent { get; set; }
            public string Prepmt_Pmt_Discount_Date { get; set; }
            public bool Prepmt_Include_Tax { get; set; }
            public string EasyShip_Freight_Terms { get; set; }
            public string Freight_Billing_Account_No { get; set; }
            public bool Do_not_Charge_Freight { get; set; }
            public bool UPS_GFP_Enable { get; set; }
            public bool Residential { get; set; }
            public string Phone_No { get; set; }
            public string Receiver_E_Mail { get; set; }
            public string Multi_Shipment_No { get; set; }
            public bool Saturday_Delivery { get; set; }
            public bool COD { get; set; }
            public string Export_Compliance_Statement { get; set; }
            public bool FedEx_Smart_Post { get; set; }
            public string Indicia { get; set; }
            public string HubId { get; set; }
            public string Date_Filter { get; set; }
            public string SalesOrderSalesLinesodatacontext { get; set; }
            public Salesordersalesline[] SalesOrderSalesLines { get; set; }
        }

        public class Salesordersalesline
        {
            public string odataetag { get; set; }
            public string Document_Type { get; set; }
            public string Document_No { get; set; }
            public int Line_No { get; set; }
            public string Type { get; set; }
            public string FilteredTypeField { get; set; }
            public string No { get; set; }
            public string Cross_Reference_No { get; set; }
            public string IC_Partner_Code { get; set; }
            public string IC_Partner_Ref_Type { get; set; }
            public string IC_Partner_Reference { get; set; }
            public string Variant_Code { get; set; }
            public bool Substitution_Available { get; set; }
            public string Purchasing_Code { get; set; }
            public bool Nonstock { get; set; }
            public string VAT_Prod_Posting_Group { get; set; }
            public string Description { get; set; }
            public bool Drop_Shipment { get; set; }
            public bool Special_Order { get; set; }
            public string Return_Reason_Code { get; set; }
            public string Package_Tracking_No { get; set; }
            public string Location_Code { get; set; }
            public string Bin_Code { get; set; }
            public string Reserve { get; set; }
            public int Quantity { get; set; }
            public int Original_Qty { get; set; }
            public int Qty_to_Assemble_to_Order { get; set; }
            public int Reserved_Quantity { get; set; }
            public string Unit_of_Measure_Code { get; set; }
            public string Unit_of_Measure { get; set; }
            public int Unit_Cost_LCY { get; set; }
            public bool SalesPriceExist { get; set; }
            public int Unit_Price { get; set; }
            public bool Tax_Liable { get; set; }
            public string Tax_Area_Code { get; set; }
            public string Tax_Group_Code { get; set; }
            public int Line_Discount_Percent { get; set; }
            public int Line_Amount { get; set; }
            public int Amount_Including_VAT { get; set; }
            public bool SalesLineDiscExists { get; set; }
            public int Line_Discount_Amount { get; set; }
            public int Prepayment_Percent { get; set; }
            public int Prepmt_Line_Amount { get; set; }
            public int Prepmt_Amt_Inv { get; set; }
            public bool Allow_Invoice_Disc { get; set; }
            public int Inv_Discount_Amount { get; set; }
            public int Inv_Disc_Amount_to_Invoice { get; set; }
            public int Qty_to_Ship { get; set; }
            public int Quantity_Shipped { get; set; }
            public int Qty_to_Invoice { get; set; }
            public int Quantity_Invoiced { get; set; }
            public int Prepmt_Amt_to_Deduct { get; set; }
            public int Prepmt_Amt_Deducted { get; set; }
            public bool Allow_Item_Charge_Assignment { get; set; }
            public int Qty_to_Assign { get; set; }
            public int Qty_Assigned { get; set; }
            public string Requested_Delivery_Date { get; set; }
            public string Promised_Delivery_Date { get; set; }
            public string Planned_Delivery_Date { get; set; }
            public string Planned_Shipment_Date { get; set; }
            public string Shipment_Date { get; set; }
            public string Shipping_Agent_Code { get; set; }
            public string Shipping_Agent_Service_Code { get; set; }
            public string Shipping_Time { get; set; }
            public string Work_Type_Code { get; set; }
            public int Whse_Outstanding_Qty { get; set; }
            public int Whse_Outstanding_Qty_Base { get; set; }
            public int ATO_Whse_Outstanding_Qty { get; set; }
            public int ATO_Whse_Outstd_Qty_Base { get; set; }
            public string Outbound_Whse_Handling_Time { get; set; }
            public string Blanket_Order_No { get; set; }
            public int Blanket_Order_Line_No { get; set; }
            public string FA_Posting_Date { get; set; }
            public bool Depr_until_FA_Posting_Date { get; set; }
            public string Depreciation_Book_Code { get; set; }
            public bool Use_Duplication_List { get; set; }
            public string Duplicate_in_Depreciation_Book { get; set; }
            public int Appl_from_Item_Entry { get; set; }
            public int Appl_to_Item_Entry { get; set; }
            public string Deferral_Code { get; set; }
            public string Shortcut_Dimension_1_Code { get; set; }
            public string Shortcut_Dimension_2_Code { get; set; }
            public string ShortcutDimCode_x005B_3_x005D_ { get; set; }
            public string ShortcutDimCode_x005B_4_x005D_ { get; set; }
            public string ShortcutDimCode_x005B_5_x005D_ { get; set; }
            public string ShortcutDimCode_x005B_6_x005D_ { get; set; }
            public string ShortcutDimCode_x005B_7_x005D_ { get; set; }
            public string ShortcutDimCode_x005B_8_x005D_ { get; set; }
            public int Quantity_Base { get; set; }
            public string SKU_Parent { get; set; }
            public string SKU_Child { get; set; }
            public bool Hide { get; set; }
            public string Tracking_No { get; set; }
            public string Tracking_URL { get; set; }
            public string Status { get; set; }
            public int Retainage_Percent { get; set; }
            public int Retainage_Amount { get; set; }
            public bool Is_Retainage_Line { get; set; }
            public string Job_No { get; set; }
            public int Special_Order_Purch_Line_No { get; set; }
            public string Special_Order_Purchase_No { get; set; }
            public int Purch_Order_Line_No { get; set; }
            public string Purchase_Order_No { get; set; }
            public string Master_Job_No { get; set; }
            public string Sell_to_Customer_No { get; set; }
            public string Job_Task_No { get; set; }
            public int TotalSalesLine_Line_Amount { get; set; }
            public int Invoice_Discount_Amount { get; set; }
            public int Invoice_Disc_Pct { get; set; }
            public int Total_Amount_Excl_VAT { get; set; }
            public int Total_VAT_Amount { get; set; }
            public int Total_Amount_Incl_VAT { get; set; }
        }

    }
}
